In [1]:
# numpy 불러오기
import numpy

In [2]:
array1=numpy.array([2,3,5,7,11,13,17,19])

In [5]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19])

In [7]:
# ndarray는 n차원 배열을 의미함
type(array1)

numpy.ndarray

In [9]:
# array1에 몇개의 요소가 있는지 확인
array1.shape

(8,)

In [11]:
array2 =numpy.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [13]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
type(array2)

numpy.ndarray

In [15]:
array2.shape

(3, 4)

In [17]:
array1.size

8

In [22]:
array2.size

6

In [ ]:
# 실습

In [23]:
import numpy

array1 = numpy.full(6,0)
array2 = numpy.random.random(6)

In [38]:
import numpy as np

array1 = np.full(6,0)
array2 = np.random.random(6)

In [39]:
array1

array([7, 7, 7, 7, 7, 7])

In [28]:
array2

array([0.90772679, 0.23762627, 0.10357241, 0.17552819, 0.23479839,
       0.34207529])