In [1]:
import numpy as np

In [2]:
array1 = np.array([2,3,5,7,11,13,15,17,19,23])

In [3]:
array1

array([ 2,  3,  5,  7, 11, 13, 15, 17, 19, 23])

In [4]:
array1[0]

2

In [5]:
array1[5]

13

In [6]:
array1[-1]

23

In [7]:
# numpy array로 인덱스 값 불러오기
array1[[1,3,4]]

array([ 3,  7, 11])

In [8]:
array2 = np.array([2,1,3])

In [9]:
# array1의 두번째 값, 첫 번째 값, 세 번째 값
array1[array2]

array([5, 3, 7])

In [10]:
array1[2:7]

array([ 5,  7, 11, 13, 15])

In [11]:
array1

array([ 2,  3,  5,  7, 11, 13, 15, 17, 19, 23])

In [12]:
# 2~6번째 인덱싱 하는데 3씩 건너 뛰고 싶다
array1[2:6:3]

array([ 5, 13])