In [1]:
import numpy as np

In [6]:
# 2중 리스트 2묶음
b = np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
# 3중 리스트 0,1,2,3,4,5 한묶음 5,4,3,2,1,0 한묶음
c = np.array([[[0,1,2],[3,4,5]],[[5,4,3],[2,1,0]]])
c

array([[[0, 1, 2],
        [3, 4, 5]],

       [[5, 4, 3],
        [2, 1, 0]]])

In [10]:
# 0이 8개 저장된 배열
d = np.zeros(8)
d

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
# 1이 8개 저장된 배열
e = np.ones(8)
e

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
# 0부터 7까지 저장된 배열
f = np.arange(8)
f

array([0, 1, 2, 3, 4, 5, 6, 7])

In [19]:
# 2x3의 2차원배열
a = np.array([[0,1,2],
             [3,4,5]])
print(np.shape(a))

(2, 3)


In [21]:
# a의 행 수 구하기
print(len(a))

2


In [23]:
a = np.array([[0,1,2],
             [3,4,5]])
print(a)
print()
print(a+3)
print()
print(a*3)

[[0 1 2]
 [3 4 5]]

[[3 4 5]
 [6 7 8]]

[[ 0  3  6]
 [ 9 12 15]]


In [28]:
b = np.array([[0,1,2],
             [3,4,5]])
c = np.array([[2,0,1],
             [5,3,4]])
print(b)
print()
print(c)
print()
print(b+c)
print()
print(b*c)
# 위의 행은 위의 행, 밑의 행은 밑의 행끼리 곱해짐
# 원래는 안되는건데 곱하기를 쓸 경우 가능

[[0 1 2]
 [3 4 5]]

[[2 0 1]
 [5 3 4]]

[[2 1 3]
 [8 7 9]]

[[ 0  0  2]
 [15 12 20]]


In [29]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a[3])

4


In [30]:
a[2]=9
print(a)

[1 2 9 4 5]


In [31]:
b = np.array([[0,1,2],
             [3,4,5]])
print(b[1,2])

5


In [32]:
b[1,2]=9
print(b)

[[0 1 2]
 [3 4 9]]


In [35]:
c = np.array([[0,1,2],
                [3,4,5]])
print(c[1,:])    # 인덱스가 1인 행만 뽑아낼 수 있음
print()
c[:,1]=np.array([6,7]) # 인덱스가 1인 열만 숫자 교체
print(c)

[3 4 5]

[[0 6 2]
 [3 7 5]]


In [36]:
a = np.array([[0,1,2],
              [3,4,5]])
print('합계:',np.sum(a))
print('평균:',np.average(a))
print('최댓값:',np.max(a))
print('최솟값:',np.min(a))

합계: 15
평균: 2.5
최댓값: 5
최솟값: 0


In [39]:
a = np.array([[0,1,2],
                 [3,4,5]])
b = np.array([[5,4,3],
             [2,1,0]])
print('곱하기:',a*b)
print('더하기:',a+b)
print('빼기:',a-b)

곱하기: [[0 4 6]
 [6 4 0]]
더하기: [[5 5 5]
 [5 5 5]]
빼기: [[-5 -3 -1]
 [ 1  3  5]]
