In [2]:
import numpy as np

a = np.array([[0,1,2],
             [1,2,3]])
b = np.array([[2,1],
                 [2,1],
                 [2,1]])
print(np.dot(a,b))
# 2x3 ,3x2 와 같이 행렬 끼리의 곱은 dot 메소드를 써야한다.

[[ 6  3]
 [12  6]]


In [7]:
a = np.array([[0,1,2],
             [3,4,5],
             [6,7,8]])
b = np.array([[0,2,0],
             [2,0,2],
             [0,2,0]])
print(np.dot(a,b))

[[ 2  4  2]
 [ 8 16  8]
 [14 28 14]]
